test_tempest: 1
prepare_tempest: 1
introspect: false
undercloud_memory: 16384
undercloud_image_url: file:///opt/oooq-images-rhel7-master/undercloud.qcow2
overcloud_image_url: file:///opt/oooq-images-rhel7-master/ironic-python-agent.tar
